# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_E8n9TkJoJ7e3kK930YidCHC_6qmWAe
"""

pip install numpy

lin_space = np.linspace(1, 100, 5)
print(lin_space)

import numpy as np
range_arr = np.arange(2,51,2)
print(range_arr)

np.random.seed(40)
rand_arr = np.random.randint(100)
print(rand_arr)

rand_float = np.random.rand()
print(rand_float)

rand_float = np.random.rand(4)
print(rand_float)

rand_int = np.random.randint(1,6, (4,3))
print(rand_int)

rand_int = np.random.randint(1,6,8)
print(rand_int)

l=['html','css','javascript','python','mysql']
rand_choice = np.random.choice(l,6)
print(rand_choice)

arr = np.array([[1, 2],[4, 5],[6,7],[8,7],[1,2],[4,5]])
print(arr.shape)

reshaped =arr.reshape(3,4)
print(reshaped)

a=np.array([[1,2,3,4],[1,2,3,4]])
flattened=a.flatten()
print(flattened)

transposed=arr.T
print(transposed)

arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

import numpy as np
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix[0:3,1])
print(matrix[1:3,2])
print(matrix[0:2,0:2])
print(matrix[1:2,1:3])

arr=np.array([4,3,5,6,30])
print(arr+10)
print(arr*2)
print(arr**0.5)

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

a=np.array([1,2,3,4,5])
print(np.mean(a))
print(np.var(a))
print(np.std(a))

print(np.min(arr))
print(np.max(arr))

arr = np.array([1,2,3,4,5])
print(np.cumsum(arr))
print(np.cumprod(arr))

arr = np.array([1,2,3,4,5,5,6,6,7,8,8,3])
print(arr%2==0)
print(arr[arr%2!=0])

arr=np.array([3,1,4,1,5,9,2,6])
sorted_arr = np.sort(arr)
print(sorted_arr)

unique_vals=np.unique(arr)
print(unique_vals)

arr = np.array([10,20,30])
view_arr = arr.view()
view_arr[0] = 100
print(arr,view_arr)

copy_arr = arr.copy()
copy_arr[0]=200
print(arr,copy_arr)

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.dot(a,b))

print(np.linalg.det(a))

print(np.linalg.inv(a))

eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)

print(eigenvectors)

c=np.array([5,11])
solution = np.linalg.solve(a,c)
print(solution)

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
vertical_stack=np.vstack((a,b))
horizontal_stack=np.hstack((a,b))
print(vertical_stack)
print(horizontal_stack)

split_arr=np.split(np.array([1,2,3,4,5,6]),3)
print(split_arr)