# -*- coding: utf-8 -*-
"""WebScraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e89ZaW0sWUFbot5Ft65znWP3d90jSkQ9
"""

#loading requirments librraries
import requests
from bs4 import BeautifulSoup

URL = "https://codegnan.com/"

# loading the webpage in memory using requests libraby
page = requests.get(URL)

#check the status code of the page
page.status_code

htmlCode = page.text
print(htmlCode)

soup = BeautifulSoup(htmlCode, 'html.parser')
print(soup)

title = soup.title.text
print("Website Title:",title)

headings=soup.find_all("h3")
for heading in headings:
    print(heading.text.strip())

links = soup.find_all("a")
for link in links[:10]:        #first 10 links
  print(link.get("href"))

images = soup.find_all("img")
for image in images:
  print(image.get("src"))

description = soup.find("meta", attrs={"name":"description"})
if description:
  print("Description:")
  print(description.get("content"))

for tag in soup.find_all():
    if tag.get("class"):
      print(tag.get("class"))

scripts = soup.find_all("scripts")
for script in scripts:
  print(script.get("src"))

logo = soup.find("img")
print(logo.get("src"))

og_image = soup.find("meta", attrs={"property":"og:image"})
if og_image:
  print(og_image.get("content"))

og_title = soup.find("meta", attrs={"property":"og:title"})
print(og_title.get("content"))

meta_tags = soup.find_all("meta")
for tag in meta_tags:
  if tag.get("name") == "description":
    print(tag.get("content"))

menus = soup.find_all("li")
for menu in menus[:20]:
  print(menu.text.strip())

paragraph = soup.find_all("p")
for para in paragraph:
  print(para.text.strip())

buttons = soup.find_all("button")
for button in buttons:
  print(button.text.strip())

images = soup.find_all("img")
for image in images:
  print(image.get("src"))

